version: '3.1'

services:
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    links:
    - mysql
    environment:
      WORDPRESS_DB_PASSWORD: 123456
    ports:
      - 8001:80
    networks:
      - back
  mysql:
    image: mariadb/server:10.3
    restart: always
    ports:
    - 8086:3306
    volumes:
       - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - back
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - back
networks:
  back:
volumes:
  db_data:
